### ISSUE TITLE
Add codex series engines: "davinci-codex" and "cushman-codex"

### ISSUE THREAD

**Issue by microsoftbuild** [dalenguyen/dalenguyen.github.io#44]
Codex series engines are in private beta as of now, but I'm hacking and building a tool that utilizes these. I would love to contribute.

**Comment by dalenguyen** [comment]
Thanks, @microsoftbuild. If you want to contribute, you can create a PR for these changes. Otherwise, I can update the package to support the codex series. 

Are you using the package at the moment?

**Comment by microsoftbuild** [comment]
Thanks, @dalenguyen. For now I am testing, definitely plan to use it down the road.

**Comment by dalenguyen** [comment]
Hi @microsoftbuild, I just update the package to v0.9.0. You can update and test it. Example usage is available here: 

https://github.com/dalenguyen/dalenguyen.github.io/blob/dev/libs/openai/tests/codex.spec.ts

**Comment by microsoftbuild** [comment]
It works! Thank you @dalenguyen.
