### ISSUE TITLE
Requesting retrieve file functionality.

### ISSUE THREAD

**Issue by microsoftbuild** [dalenguyen/dalenguyen.github.io#49]
Hi @dalenguyen 

There are two functionalities i.e. retrieve file and retrieve file contents, that are offered by the OpenAI API.Requesting you to please add them. I'd also love to contribute but haven't worked on writing packages.

Link for reference: https://beta.openai.com/docs/api-reference/files/retrieve

**Comment by dalenguyen** [comment]
It's already there. Can you try it? 

```
  // FILES
  listFiles()

  retrieveFile(fileId: string)

  retrieveFileContent(fileId: string)

  uploadFile(data: FileRequest)

  deleteFile(fileId: string)
```

**Comment by microsoftbuild** [comment]
Thanks for the help @dalenguyen 

I didn't see this in the readme. Hence asked.
